#! /usr/bin/php
<?php
define('DEBUG', 'on');
define('WEBPATH', __DIR__);

require __DIR__ . '/../../../vendor/autoload.php';
Swoole\Loader::vendor_init();


$setting['worker_num'] = 4;
$setting['daemonize'] = 1;

$svr = new App\AutoInterface();
$svr->setLogger(new Swoole\Log\FileLog(__DIR__.'/../../log/auto_interface.log'));
$setting['pid_file'] = __DIR__.'/../../run/auto_interface.pid';
$svr->run($setting);